### PR TITLE
Notebook to display coadd images

### PR DESCRIPTION
**Pull request by kadrlica**
This is the result of a breakout hack using the butler to grab coadded images.

### CODE REVIEW

**Comment by kadrlica** [comment]
@saharallam or @mpwiesner would either of you be willing to review this notebook from our last delegate assembly breakout?

**Comment by mpwiesner** [comment]
Sure, I can review it tomorrow morning before the assembly.

**Comment by mpwiesner** [comment]
This notebook ran just fine for me, no problems I could see. Thanks, Alex!

**Review by mpwiesner — COMMENTED** [review]
Looks good!

**Comment by kadrlica** [comment]
Awesome, thanks Matt!

**Pull request merged**
